services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: "SECURE_PASSWORD_123"
    ports:
      - "1433:1433"
    volumes:
      - ./data/:/var/opt/mssql/data/
volumes:
  mssql: